# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod.name=Optimal Aim
mod.id=optimalaim
mod.version=1.0.6
mod.group=me.sootysplash.optimalaim
mod.description=This mod renders a cube at the best place to aim for optimal reach utilization.
mod.source=https://github.com/sootysplash/optimal-aim
mod.issues=https://github.com/sootysplash/optimal-aim/issues
mod.license=Apache-2.0
mod.modrinth=https://modrinth.com/mod/optimal-aim
mod.curseforge=https://www.curseforge.com/minecraft/mc-mods/optimal-aim
mod.github=https://github.com/sootysplash

# Publishing
publish.modrinth=
publish.curseforge=

# Dependencies
deps.fabric_loader_version=0.17.2
deps.devauth_version=1.2.1
deps.mixinconstraints_version=1.1.0
deps.mixinsquared_version=0.2.0
deps.yacl_version=3.7.1
deps.omnicore_version=1.0.0-beta.1
deps.omnicore_version=1.0.0-beta.10

# Build Plugins
# in libs.versions.toml

# Minecraft properties
mod.mc_dep=[VERSIONED]
mod.mc_version=[VERSIONED]

# Versioned
deps.parchment_version=[VERSIONED]
deps.fabric_api_version=[VERSIONED]
deps.modmenu_version=[VERSIONED]

deps.neoforge_version=[VERSIONED]

loom.ignoreDependencyLoomVersionValidation=true
